### ISSUE TITLE
Fail to build arc-archs-linux-gnu: 'memchr' specified bound 4294967295 exceeds maximum object size 2147483647

### ISSUE THREAD

**Issue by falaleevms** [foss-for-synopsys-dwc-arc-processors/gcc#100]
arc-archs-linux-gnu toolchain building failed during glibc building:

```
arc-snps-linux-gnu-gcc -O2 -Werror -c rawmemchr.i  
In function '__rawmemchr',
    inlined from '__rawmemchr' at rawmemchr.c:27:1:
rawmemchr.c:40:12: error: 'memchr' specified bound 4294967295 exceeds maximum object size 2147483647 [-Werror=stringop-overread]
   40 |     return memchr (s, c, (size_t)-1);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~
```

Gcc version: e0d16f23eef arc64/arcv3: Check BE for TLS.
Glibc version: `glibc-2.33`

Attaching [rawmemchr.i.txt](https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/files/7077865/rawmemchr.i.txt)

**Comment by abrodkin** [comment]
Upstream problem reported against GCC: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=98512, solution deferred till GCC 12
Work-around for glibc: https://sourceware.org/git/?p=glibc.git;a=commit;h=044e603b698093cf48f6e6229e0b66acf05227e4 which is a part of glibc 2.34 (was submitted too late for 2.33, but later committed in 2.33 branch https://sourceware.org/git/?p=glibc.git;a=commit;h=8d4241b8976273513e72cc1c5f6b1af3e11f0792).

I suggest we switch to glibc 2.34 (vanilla for ARCompact/ARCv2 & https://github.com/foss-for-synopsys-dwc-arc-processors/glibc/commits/arc64-2.34).

@claziss what would you say?
