### ISSUE TITLE
error: unrecognizable insn

### ISSUE THREAD

**Issue by Chen-Gang** [foss-for-synopsys-dwc-arc-processors/gcc#27]
Summary:

  For Public Linux kernel next-20130927 tree, it will cause compiling issue.

The related operation:

  for Linux next-20130927 tree
  make ARCH=arc CROSS_COMPILE=/usr/local/bin/arc-elf32- allmodconfig
  make ARCH=arc CROSS_COMPILE=/usr/local/bin/arc-elf32-

The related error:

```
CC [M]  drivers/target/target_core_pr.o
```

  drivers/target/target_core_pr.c: In function 'target_scsi3_emulate_pr_in':
  drivers/target/target_core_pr.c:4033:1: error: unrecognizable insn:
   }
   ^
  (insn 846 194 196 12 (set (reg:QI 1 r1)
          (subreg:QI (mem/j/c:DI (plus:SI (reg/v/f:SI 2 r2 [orig:199 pr_reg ] [199])
                      (const_int 576 [0x240])) [0 pr_reg_50->pr_res_key+0 S8 A32]) 7)) drivers/target/target_core_pr.c:3677 -1
       (nil))
  drivers/target/target_core_pr.c:4033:1: internal compiler error: in extract_insn, at recog.c:2151
  0x758fb5 _fatal_insn(char const_, rtx_def const_, char const_, int, char const_)
        ../../gcc/gcc/rtl-error.c:109
  0x758fe9 _fatal_insn_not_found(rtx_def const_, char const_, int, char const_)
        ../../gcc/gcc/rtl-error.c:117
  0x726e83 extract_insn(rtx_def_)
        ../../gcc/gcc/recog.c:2151
  0x726ef4 extract_insn_cached(rtx_def_)
        ../../gcc/gcc/recog.c:2054
  0x5fe026 cleanup_subreg_operands(rtx_def_)
        ../../gcc/gcc/final.c:3305
  0x750c2e reload(rtx_def_, int)
        ../../gcc/gcc/reload1.c:1240
  0x68e703 do_reload
        ../../gcc/gcc/ira.c:4631
  0x68e703 rest_of_handle_reload
        ../../gcc/gcc/ira.c:4731
  Please submit a full bug report,
  with preprocessed source if appropriate.
  Please include the complete backtrace with any bug report.
  See http://gcc.gnu.org/bugs.html for instructions.
  make[2]: *_\* [drivers/target/target_core_pr.o] Error 1
  make[1]: **\* [drivers/target] Error 2
  make: **\* [drivers] Error 2

The related information:

  [root@gchenlinux linux-next]# /usr/local/bin/arc-elf32-gcc -v
  Using built-in specs.
  COLLECT_GCC=/usr/local/bin/arc-elf32-gcc
  COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/arc-elf32/4.8.0/lto-wrapper
  Target: arc-elf32
  Configured with: ../gcc/configure --without-header --disable-nls --enable-language=c --disable-threads --disable-shared --enable-werror=no target_configargs=enable_vtable_verify=yes --target=arc-elf32 --with-cpu=arc700 : (reconfigured) ../gcc/configure --disable-nls --enable-language=c --disable-threads --disable-shared --enable-werror=no target_configargs=enable_vtable_verify=yes --target=arc-elf32 --with-cpu=arc700 : (reconfigured) ../gcc/configure --without-header --disable-nls --enable-language=c --disable-threads --disable-shared --enable-werror=no target_configargs=enable_vtable_verify=yes --target=arc-elf32 --with-cpu=arc700 --disable-multilib --with-headers=../newlib/newlib/libc/include
  Thread model: single
  gcc version 4.8.0 (GCC)

Next, I will/should provide preprocessed source of test cases and compiler flags to repeat this issue, within 2013-10-31.

**Comment by Chen-Gang** [comment]
After shrinking:

The command: arc-elf32-gcc -Os -c target_core_pr.i
It is not gnu issue (gnu gcc 4.8/4.9 for x86 is OK).
The demo source file is about 1K lines (shrank from 50K lines to 1K lines), although it is still a big file which can be shrunk more.

Excuse me, I don't know how to past this file on this website, so I will send attachment in the related mailing list.

**Comment by claziss** [comment]
This issue is fixed in arc-dev branch. Have you try it?

**Comment by Chen-Gang** [comment]
On 10/31/2013 05:02 PM, Claudiu Zissulescu wrote:

> This issue is fixed in arc-dev branch. Have you try it?

I guess, I am not. Excuse me, I am a newbie, please provide more
information about it (e.g. git link, git tag full name ...).

After get the related version, I will/should finish trying within
2013-11-30.

Thanks.

> —
> Reply to this email directly or view it on GitHub
> https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/issues/27#issuecomment-27470760.

## 

Chen Gang

**Comment by jeremybennett** [comment]
Hi Chen-Gang,

I assume you are building the toolchain from the `build-all.sh` script in the [toolchain repository](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain). From that repo checkout the [arc-4.8-dev branch](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/tree/arc-4.8-dev). Within your local toolchain repository clone directlry, you can do this using

```
git checkout arc-4.8-dev
```

If you run `build-all.sh`, then by default it will checkout the development branches of all the other repositories corresponding to the 4.8 tool chain release.

HTH,

Jeremy

**Comment by Chen-Gang** [comment]
On 10/31/2013 05:34 PM, Jeremy Bennett wrote:

> Hi Chen-Gang,
> 
> I assume you are building the toolchain from the |build-all.sh| script
> in the toolchain repository
> https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain.
> From that repo checkout the arc-4.8-dev branch
> https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/tree/arc-4.8-dev.
> Within your local toolchain repository clone directlry, you can do this
> using
> 
> |git checkout arc-4.8-dev
> |
> 
> If you run |build-all.sh|, then by default it will checkout the
> development branches of all the other repositories corresponding to the
> 4.8 tool chain release.

OK, I will/should try within next week (within 2013-11-10). And my current information is below:

The binary information:

  [root@gchenlinux ana]# /usr/local/bin/arc-elf32-gcc -v
  Using built-in specs.
  COLLECT_GCC=/usr/local/bin/arc-elf32-gcc
  COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/arc-elf32/4.8.0/lto-wrapper
  Target: arc-elf32
  Configured with: ../gcc/configure --without-header --disable-nls --enable-language=c --disable-threads --disable-shared --enable-werror=no target_configargs=enable_vtable_verify=yes --target=arc-elf32 --with-cpu=arc700 : (reconfigured) ../gcc/configure --disable-nls --enable-language=c --disable-threads --disable-shared --enable-werror=no target_configargs=enable_vtable_verify=yes --target=arc-elf32 --with-cpu=arc700 : (reconfigured) ../gcc/configure --without-header --disable-nls --enable-language=c --disable-threads --disable-shared --enable-werror=no target_configargs=enable_vtable_verify=yes --target=arc-elf32 --with-cpu=arc700 --disable-multilib --with-headers=../newlib/newlib/libc/include
  Thread model: single
  gcc version 4.8.0 (GCC) 

The source code version:

  [root@gchenlinux gcc]# git log -n1 --oneline
  4c4731f Merge pull request #15 from foss-for-synopsys-dwc-arc-processors/anton-testsuite-linker-plugin2
  [root@gchenlinux gcc]# git tag
  arc_4_4-release
  arc_4_8-R1
  arc_4_8-R1.1
  arc_4_8-R1.2
  arc_4_8-evb1
  arc_4_8-evb2
  arc_4_8-evb3
  arc_4_8-evb4
  arc_4_8-evb5
  gcc-4_4_7-branchpoint
  [root@gchenlinux gcc]# git branch
- arc-4.8-stable

The build operation:

  export TARGET=arc-elf32
  configure like "gcc -v" shows above
  make all-gcc
  make all-target-gcc
  make install-gcc
  make install-target-libgcc

> HTH,
> 
> Jeremy
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/issues/27#issuecomment-27472319.

## 

Chen Gang

**Comment by Chen-Gang** [comment]
For gcc-arc-4.8-dev, it is OK -- can not cause issue again. So I close it.
