### ISSUE TITLE
internal compiler error: in arc_ifcvt, at config/arc/arc.c:8315

### ISSUE THREAD

**Issue by Chen-Gang** [foss-for-synopsys-dwc-arc-processors/gcc#28]
Summary:

For Public Linux kernel next-20130927 tree, it will cause compiling issue.

The related operation:

make ARCH=arc CROSS_COMPILE=/usr/local/bin/arc-elf32- allmodconfig
make ARCH=arc CROSS_COMPILE=/usr/local/bin/arc-elf32- menuconfig (disable CONFIG_CC_OPTIMIZE_FOR_SIZE)
make ARCH=arc CROSS_COMPILE=/usr/local/bin/arc-elf32- EXTRA_CFLAGS=-mmedium-calls

The related error:

CC [M]  drivers/target/target_core_pr.o

  CC [M]  net/ipv4/netfilter/nf_nat_h323.o
net/ipv4/netfilter/nf_nat_h323.c: In function 'nat_rtp_rtcp':
net/ipv4/netfilter/nf_nat_h323.c:275:1: internal compiler error: in arc_ifcvt, at config/arc/arc.c:8315
 }
 ^
0x939c94 arc_ifcvt
    ../../gcc/gcc/config/arc/arc.c:8315
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See http://gcc.gnu.org/bugs.html for instructions.
make[3]: **\* [net/ipv4/netfilter/nf_nat_h323.o] Error 1
make[2]: **\* [net/ipv4/netfilter] Error 2
make[1]: **\* [net/ipv4] Error 2
make: **\* [net] Error 2

The related information:

[root@gchenlinux linux-next]# /usr/local/bin/arc-elf32-gcc -v
Using built-in specs.
COLLECT_GCC=/usr/local/bin/arc-elf32-gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/arc-elf32/4.8.0/lto-wrapper
Target: arc-elf32
Configured with: ../gcc/configure --without-header --disable-nls --enable-language=c --disable-threads --disable-shared --enable-werror=no target_configargs=enable_vtable_verify=yes --target=arc-elf32 --with-cpu=arc700 : (reconfigured) ../gcc/configure --disable-nls --enable-language=c --disable-threads --disable-shared --enable-werror=no target_configargs=enable_vtable_verify=yes --target=arc-elf32 --with-cpu=arc700 : (reconfigured) ../gcc/configure --without-header --disable-nls --enable-language=c --disable-threads --disable-shared --enable-werror=no target_configargs=enable_vtable_verify=yes --target=arc-elf32 --with-cpu=arc700 --disable-multilib --with-headers=../newlib/newlib/libc/include
Thread model: single
gcc version 4.8.0 (GCC)

**Comment by Chen-Gang** [comment]
It seems the same issue to #26, so after #26 is fixed, I will try it again

**Comment by claziss** [comment]
We do not see any longer this issue.
