### ISSUE TITLE
Segment fault for arc-gcc-4.8-dev

### ISSUE THREAD

**Issue by Chen-Gang** [foss-for-synopsys-dwc-arc-processors/gcc#30]
For arc-gcc-4.8-dev, linux kernel next-20131107.

Operation:

  make ARCH=arc CROSS_COMPILE=/usr/local/bin/arc-elf32- EXTRA_CFLAGS=-mmedium-calls allmodconfig
  make ARCH=arc CROSS_COMPILE=/usr/local/bin/arc-elf32- EXTRA_CFLAGS=-mmedium-calls menuconfig
    disable CPU_BIG_ENDIAN
    disable CC_OPTIMIZE_FOR_SIZE
  make ARCH=arc CROSS_COMPILE=/usr/local/bin/arc-elf32- EXTRA_CFLAGS=-mmedium-calls

Error:

   CC [M]  fs/hfs/string.o
  fs/hfs/string.c: In function 'hfs_strcmp':
  fs/hfs/string.c:89:1: internal compiler error: Segmentation fault
   }
   ^
  0x7a1faf crash_signal
        ../../gcc-arc-4.8-dev/gcc/toplev.c:332
  0x93fa27 df_get_live_in
        ../../gcc-arc-4.8-dev/gcc/df.h:1109
  0x93fa27 arc_hazard
        ../../gcc-arc-4.8-dev/gcc/config/arc/arc.c:7995
  0x93fa27 arc_hazard
        ../../gcc-arc-4.8-dev/gcc/config/arc/arc.c:7966
  0x944967 get_attr_in_delay_slot(rtx_def_)
        ../../gcc-arc-4.8-dev/gcc/config/arc/arc.md:441
  0x945dff get_attr_in_ret_delay_slot(rtx_def_)
        ../../gcc-arc-4.8-dev/gcc/config/arc/arc.md:367
  0x94787e get_attr_cond_ret_delay_insn(rtx_def_)
        ../../gcc-arc-4.8-dev/gcc/config/arc/arc.md:722
  0x95e7d7 eligible_for_annul_false(rtx_def_, int, rtx_def_, int)
        ../../gcc-arc-4.8-dev/gcc/config/arc/arc.md:1104
  0x75679e make_return_insns
        ../../gcc-arc-4.8-dev/gcc/reorg.c:3611
  0x75679e dbr_schedule(rtx_def_)
        ../../gcc-arc-4.8-dev/gcc/reorg.c:3764
  0x756d7f rest_of_handle_delay_slots
        ../../gcc-arc-4.8-dev/gcc/reorg.c:3891
  Please submit a full bug report,

gcc Information:

  [root@gchenlinux linux-next]# arc-elf32-gcc -v
  Using built-in specs.
  COLLECT_GCC=arc-elf32-gcc
  COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/arc-elf32/4.8.0/lto-wrapper
  Target: arc-elf32
  Configured with: ../gcc-arc-4.8-dev/configure --without-header --disable-nls --enable-language=c --disable-threads --disable-shared --enable-werror=no target_configargs=enable_vtable_verify=yes --target=arc-elf32 --with-cpu=arc700 --disable-multilib --with-headers=../newlib/newlib/libc/include
  Thread model: single
  gcc version 4.8.0 (GCC)

After simplify:

  command: ./cc1 /tmp/string.i -O2 -fno-reorder-blocks
  /tmp/string.i contents:

  1 static unsigned char caseorder[256] = {
  2  0x00,0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,0x09,0x0A,0x0B,0x0C,0x0D,0x0E,0x0F,
  3  0x10,0x11,0x12,0x13,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B,0x1C,0x1D,0x1E,0x1F,
  4  0x20,0x22,0x23,0x28,0x29,0x2A,0x2B,0x2C,0x2F,0x30,0x31,0x32,0x33,0x34,0x35,0x36,
  5  0x37,0x38,0x39,0x3A,0x3B,0x3C,0x3D,0x3E,0x3F,0x40,0x41,0x42,0x43,0x44,0x45,0x46,
  6  0x47,0x48,0x57,0x59,0x5D,0x5F,0x66,0x68,0x6A,0x6C,0x72,0x74,0x76,0x78,0x7A,0x7E,
  7  0x8C,0x8E,0x90,0x92,0x95,0x97,0x9E,0xA0,0xA2,0xA4,0xA7,0xA9,0xAA,0xAB,0xAC,0xAD,
  8  0x4E,0x48,0x57,0x59,0x5D,0x5F,0x66,0x68,0x6A,0x6C,0x72,0x74,0x76,0x78,0x7A,0x7E,
  9  0x8C,0x8E,0x90,0x92,0x95,0x97,0x9E,0xA0,0xA2,0xA4,0xA7,0xAF,0xB0,0xB1,0xB2,0xB3,
 10  0x4A,0x4C,0x5A,0x60,0x7B,0x7F,0x98,0x4F,0x49,0x51,0x4A,0x4B,0x4C,0x5A,0x60,0x63,
 11  0x64,0x65,0x6E,0x6F,0x70,0x71,0x7B,0x84,0x85,0x86,0x7F,0x80,0x9A,0x9B,0x9C,0x98,
 12  0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0x94,0xBB,0xBC,0xBD,0xBE,0xBF,0xC0,0x4D,0x81,
 13  0xC1,0xC2,0xC3,0xC4,0xC5,0xC6,0xC7,0xC8,0xC9,0xCA,0xCB,0x55,0x8A,0xCC,0x4D,0x81,
 14  0xCD,0xCE,0xCF,0xD0,0xD1,0xD2,0xD3,0x26,0x27,0xD4,0x20,0x49,0x4B,0x80,0x82,0x82,
 15  0xD5,0xD6,0x24,0x25,0x2D,0x2E,0xD7,0xD8,0xA6,0xD9,0xDA,0xDB,0xDC,0xDD,0xDE,0xDF,
 16  0xE0,0xE1,0xE2,0xE3,0xE4,0xE5,0xE6,0xE7,0xE8,0xE9,0xEA,0xEB,0xEC,0xED,0xEE,0xEF,
 17  0xF0,0xF1,0xF2,0xF3,0xF4,0xF5,0xF6,0xF7,0xF8,0xF9,0xFA,0xFB,0xFC,0xFD,0xFE,0xFF
 18 };
 19 int hfs_strcmp(const unsigned char _s1, unsigned int len1, const unsigned char *s2, unsigned int len2)
 20 {
 21  int len, tmp;
 22 
 23  len = (len1 > len2) ? len2 : len1;
 24  while (len--) {
 25   tmp = (int)caseorder[_(s1++)] - (int)caseorder[*(s2++)];
 26   if (tmp)
 27    return tmp;
 28  }
 29  return len1 - len2;
 30 }

**Comment by Chen-Gang** [comment]
In arc_hazard() gcc/config/arc/arc.c, if 'lab' is 'simple_return_rtx',
it will cause segment fault, so need check it. After skip it, can let
this issue solved.

---------------------------diff begin-----------------------------------

--- gcc/config/arc/arc.c        2013-11-11 13:01:38.032630106 +0800
+++ gcc/config/arc/arc.gchen.c  2013-11-11 13:01:27.680755551 +0800
@@ -7988,6 +7988,8 @@ arc_hazard (rtx pred, rtx succ)
              /\* Go to the target of the jump and check for aliveness
                 of LP_COUNT register. */
              && (!(lab = JUMP_LABEL (jump))
-                  || (lab == simple_return_rtx)
-                  || (lab == ret_rtx)
                || (!(succ_bb = BLOCK_FOR_INSN (lab))
                    && (!NOTE_INSN_BASIC_BLOCK_P (NEXT_INSN (lab))
                        || ! (succ_bb = NOTE_BASIC_BLOCK (NEXT_INSN (lab))))

---------------------------diff end-------------------------------------

Please help check, thanks (it is just a demo fix, may have additional better fix).

**Comment by jeremybennett** [comment]
Hi Chen-Gang,

I've asked amylaar (Joern Rennecke) to take a look.

Jeremy

**Comment by claziss** [comment]
This issue is fixed in dev branch by commit https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/a2ed3cfb9d600af47d5f87cb509cb8ef90104780

**Comment by Chen-Gang** [comment]
After have a look, for me, this issue is related with commit a2ed3cf, my demo fix is based on the commit a2ed3cf (I use the source code: gcc-arc-4.8-dev.zip).

Please check the code below, the line 7991 and 7992 is added by me, this code is already based on commit a2ed3cf.

7965 int
7966 arc_hazard (rtx pred, rtx succ)
7967 {
7968   rtx jump, lab;
7969   basic_block succ_bb;
7970 
7971   if (!pred || !INSN_P (pred) || !succ || !INSN_P (succ))
7972     return 0;
7973   /\* We might have a CALL to a non-returning function before a loop
7974      end.  ??? Although the manual says that's OK (the target is
7975      outside the loop, and the loop counter unused there), the
7976      assembler barfs on this for ARC600, so we must instert a nop
7977      before such a call too.  _/
7978   if (recog_memoized (succ) == CODE_FOR_doloop_end_i
7979       && ((TARGET_ARC600
7980            && (JUMP_P (pred) || CALL_P (pred)
7981                || GET_CODE (PATTERN (pred)) == SEQUENCE))
7982           /_ Check if it is a jump. _/
7983           || ((JUMP_P ((jump = pred))
7984                || (GET_CODE (PATTERN (pred)) == SEQUENCE
7985                    && JUMP_P ((jump = XVECEXP (PATTERN (pred), 0, 0)))))
7986               /_ Make sure is not a simple_return. _/
7987               && (GET_CODE (PATTERN (jump)) != SIMPLE_RETURN)
7988               /_ Go to the target of the jump and check for aliveness
7989                  of LP_COUNT register. */
7990               && (!(lab = JUMP_LABEL (jump))
7991                   || (lab == simple_return_rtx)
7992                   || (lab == ret_rtx)
7993                   || (!(succ_bb = BLOCK_FOR_INSN (lab))
7994                       && (!NOTE_INSN_BASIC_BLOCK_P (NEXT_INSN (lab))
7995                           || ! (succ_bb = NOTE_BASIC_BLOCK (NEXT_INSN (lab))))
7996                       && !(succ_bb = BLOCK_FOR_INSN (NEXT_INSN (lab))))
7997                   || (REGNO_REG_SET_P (df_get_live_in (succ_bb), LP_COUNT))))))
7998     return 4;
7999 
8000   if (TARGET_ARC600)
8001     return arc600_corereg_hazard (pred, succ);
8002 
8003   return 0;
8004 }
