### ISSUE TITLE
how to have FSDIV instruction supported by arc gcc

### ISSUE THREAD

**Issue by ardeal** [foss-for-synopsys-dwc-arc-processors/gcc#47]
Hi Prof.

In my Makefile, I add the following options to enable arc float HW instructions:
EXTRA_CFLAGS += -mcpu=ARCv2EM -mdiv-rem -mbarrel-shifter -mspfp
By the above commands, fsadd, fsmul, and fssub can be correctly supported by arc gcc and HW instructions.
But float divsion, float to int, int to float and float comparison are not supported by arc gcc natively and correctly.
Can you tell me how to enable those 4 HW instructions?

**Comment by claziss** [comment]
Hi,
-mspfp refers to old ARC FPX extensions and are not supported by new ARCv2 processors. A correct option line will be:
-mcpu=arcem -mdiv-rem -mfpu=fpus -mbarrel-shifter
That will confer u basic single precision floating point HW support. For more information about mfpu options please refer to our manual.
Please let us know if the documentation is missing information.

**Comment by ardeal** [comment]
Hi 
My C code and dessembled code is as follows. 
fsadd and fsmul are correctly included by arc -gcc compiler, but fsdiv is not correctly included by arc-gcc compiler.

```
float a=0.4563f, b = 0.32324f, c=0.0f, e = 0.0f;
a=i2f(ax) + a; //ax is a variable
b = i2f(ay) + b; //ay is a variable
c=e+a*b;
c = c*e;
c = c/a;
pr_info(LOG_MODULE_OPEN_CORE, "---------------%f\n",c);
```

40042954:   fe 1d 0c 90                 sth.a      r0,[r13,-2]
40042958:   2f 39 2c 04                 ???        r44,r1,r16
4004295c:   01 31 81 0f e9 3e 27 a0     fsadd      r1,r1,0x3ee9a027
40042964:   2f 38 ec 03                 ???        r44,r0,r15
40042968:   01 30 80 0f a5 3e b7 7f     fsadd      r0,r0,0x3ea57fb7
40042970:   00 31 00 00                 fsmul      r0,r1,r0
40042974:   41 30 00 00                 fsadd      r0,r0,0
40042978:   40 30 00 00                 fsmul      r0,r0,0
4004297c:   fe 0e 00 04                 bl         4004b078 __divsf3

40042980:   fe 0b 60 04                 bl.d       4004b57c __extendsfdf2

40042984:   10 43                       mov_s      r19,r0
40042986:   c3 42 05 40 ec 24           mov_s      r2,0x400524ec
4004298c:   00 43                       mov_s      r3,r0
4004298e:   20 44                       mov_s      r4,r1
40042990:   0c 72                       mov_s      r0,2
40042992:   86 0a af ff                 bl.d       40041c14 log_printk

the dessemabled code at 4004b078  is as follows. it seems that float div is implementd by software but not hw fsdiv.
How to have float div implemented by fsdiv hw instructions?
4004b078 __divsf3:
4004b078:   f1 c0                       push_s     blink
4004b07a:   aa c1                       sub_s      sp,sp,40
4004b07c:   00 1c 00 30                 st         r0,[sp]
4004b080:   04 1c 40 30                 st         r1,[sp,4]
4004b084:   83 40                       mov_s      r0,sp
4004b086:   ce 0d ef ff                 bl.d       4004ae50 __unpack_f

**Comment by ardeal** [comment]
Hi,
Do you have the document about options to enable hw instructions like
 -mfpu=fpus
?
Can you share the detailed document?

**Comment by ardeal** [comment]
Hi Prof.
Currently, in my Makefile, I use ARCv2EM for my ARC version, but I am not sure whether it is exactly correct. is there a way to check the version of my ARC?

**Comment by anthony-kolesov** [comment]
Hi @ardeal,

To figure out exact version of CPU you need to read IDENTITY register. See ARC v2 PRM on what is the contents of this register.

GCC manual in share/doc/gcc/gcc.pdf has a list of -mfpu= values and what do they mean. There is no exact list of what are the exact instructions added by each option, but that can be derived from ARC v2 PRM.

Can you also post full test case with all compiler options.

**Comment by claziss** [comment]
Hi
As far as I see from the dissassembly, you don't pass any optimization level to the compiler. Please can u use -O2 (for example). The default gcc compiler optimization level is set to zero. 

Also, there may be a chance the compiler will optimize out your code if it can.

Thanks.

**Comment by ardeal** [comment]
Hi Anthony and Claziss,
Many thanks for your quick response!
My test C code and corresponding dessembled code is as follows.

after readding gcc.pdf, I used the following options:
-mcpu=arcem -mdiv-rem -mfpu=fpus_all -mbarrel-shifter

The dessembled code is correct to my expection, but the code cannot be run on my ARC. I got the following panic issue when I run the test code:
PANIC for 1 (dump located on 0xa8014000)
ARC BUILD CKSUM: 93e43ff9 
ARC BUILD VERSION: 00000001 
ARC PANIC - eret=0x40039162 - sp=0xa8013af0

---

Test C code:
   float a=0.4563f, b = 0.32324f, c=0.0f, e = 0.0f;
    a=i2f(ax) + a;
    b = i2f(ay) + b;
    c=e+a_b;
    c = c_e;
    c = c/a;
    c = c\* ax;
    if(c>5.6f)
        c=3.2f;
    pr_info(LOG_MODULE_OPEN_CORE, "---------------%f\n",c);

---

Corresponding dessembled code:
40042950:   2f 38 ac 03                 ???        r44,r0,r14
40042954:   01 30 80 0f e9 3e 27 a0     fsadd      r0,r0,0x3ee9a027
4004295c:   2f 39 2c 04                 ???        r44,r1,r16
40042960:   48 36 82 10                 fcvt32     r2,r14,2
40042964:   01 31 81 0f a5 3e b7 7f     fsadd      r1,r1,0x3ea57fb7
4004296c:   00 30 41 00                 fsmul      r1,r0,r1
40042970:   41 31 01 00                 fsadd      r1,r1,0
40042974:   40 31 01 00                 fsmul      r1,r1,0
40042978:   07 31 01 00                 fsdiv      r1,r1,r0
4004297c:   00 31 81 00                 fsmul      r1,r1,r2
40042980:   03 31 80 8f b3 40 33 33     fscmp      r1,0x40b33333
40042988:   0a 20 80 0f 4c 40 cd cc     mov        r0,0x404ccccd
40042990:   ba 0b 60 04                 bl.d       4004b548 __extendsfdf2

40042994:   ca 20 4c 00                 mov.le     r0,r1
40042998:   c3 42 05 40 b4 24           mov_s      r2,0x400524b4
4004299e:   00 43                       mov_s      r3,r0
400429a0:   20 44                       mov_s      r4,r1
400429a2:   0c 72                       mov_s      r0,2
400429a4:   76 0a af ff                 bl.d       40041c18 log_printk

**Comment by ardeal** [comment]
If I use the following option line:
EXTRA_CFLAGS += -mcpu=ARCv2EM -mdiv-rem -mbarrel-shifter -mspfp
The generated dessembled code is as follows, and it can be correctly run on ARC.
40042958:   2f 3b 2c 00                 ???        r44,r3,r0
4004295c:   01 33 81 0f e9 3e 27 a0     fsadd      r1,r3,0x3ee9a027
40042964:   2f 38 2c 00                 ???        r44,r0,r0
40042968:   01 30 80 0f a5 3e b7 7f     fsadd      r0,r0,0x3ea57fb7
40042970:   00 31 00 00                 fsmul      r0,r1,r0
40042974:   41 30 00 00                 fsadd      r0,r0,0
40042978:   40 30 00 00                 fsmul      r0,r0,0
4004297c:   9e 08 40 04                 bl         4004b218 __divsf3

40042980:   08 46                       mov_s      r14,r0
40042982:   ee 0b 60 04                 bl.d       4004b56c __floatsisf

40042986:   a1 40                       mov_s      r0,r13
40042988:   00 36 0e 10                 fsmul      r14,r14,r0
4004298c:   0a 21 80 0f b3 40 33 33     mov        r1,0x40b33333
40042994:   9e 0a 60 04                 bl.d       4004b430 __gtsf2

40042998:   c1 40                       mov_s      r0,r14
4004299a:   14 70                       cmp_s      r0,0
4004299c:   0a 20 80 0f 4c 40 cd cc     mov        r0,0x404ccccd
400429a4:   7a 0d 60 04                 bl.d       4004b71c __extendsfdf2

400429a8:   ca 20 8c 03                 mov.le     r0,r14
400429ac:   c3 42 05 40 8c 26           mov_s      r2,0x4005268c
400429b2:   00 43                       mov_s      r3,r0
400429b4:   20 44                       mov_s      r4,r1
400429b6:   0c 72                       mov_s      r0,2
400429b8:   76 0a af ff                 bl.d       40041c2c log_printk

If I use the following option line:
EXTRA_CFLAGS += -mcpu=arcem -mdiv-rem -mfpu=fpus -mbarrel-shifter

the generated dessembled code is as follows, ant ARC will go panic:
40042938:   2f 3b 2c 00                 ???        r44,r3,r0
4004293c:   01 33 81 0f e9 3e 27 a0     fsadd      r1,r3,0x3ee9a027
40042944:   2f 38 2c 00                 ???        r44,r0,r0
40042948:   01 30 80 0f a5 3e b7 7f     fsadd      r0,r0,0x3ea57fb7
40042950:   00 31 00 00                 fsmul      r0,r1,r0
40042954:   41 30 00 00                 fsadd      r0,r0,0
40042958:   40 30 00 00                 fsmul      r0,r0,0
4004295c:   46 0f 00 04                 bl         4004b0a0 __divsf3

40042960:   48 35 83 10                 fcvt32     r3,r13,2
40042964:   00 30 c3 00                 fsmul      r3,r0,r3
40042968:   03 33 80 8f b3 40 33 33     fscmp      r3,0x40b33333
40042970:   0a 20 80 0f 4c 40 cd cc     mov        r0,0x404ccccd
40042978:   2e 0c 60 04                 bl.d       4004b5a4 __extendsfdf2

4004297c:   ca 20 cc 00                 mov.le     r0,r3
40042980:   c3 42 05 40 14 25           mov_s      r2,0x40052514
40042986:   00 43                       mov_s      r3,r0
40042988:   20 44                       mov_s      r4,r1
4004298a:   0c 72                       mov_s      r0,2
4004298c:   8a 0a af ff                 bl.d       40041c14 log_printk

According to my experiments, the result can be summarized as follows:
1) mspfp option use fsadd, fsmul and fssub which are provided by arc extension instructions. The code can be run correctly on ARC.
2) fpus option use fsadd, fsmul, fssub, fsdiv and fscmp which are provided by arc extension too. The code can not be run correctly on ARC.

my questions are:
1) mspfp option and fpus option use the same instruction set, why can the code generated by mspfp be run on ARC correctly but that generated by fpus cannot be run on ARC?
2) is there a way to have fsdiv, fscmp and fscvt32 generated by mspfp as well?
3) there are the following ARC extension instructions in manual:
DSP_FP_DIV
DSP_FP_FLT2I
DSP_FP_I2FLT
DSP_FP_CMP
DSP_FP_SQRT
FP_ADD
FP_SUB
FP_MUL

The last 3 instructions can be supported by ARC gcc natively, but the first 5 can not be supported by ARC gcc natively with option mspfp on my ARC. is there a way to have the first 5 supported by ARC gcc natively?

**Comment by anthony-kolesov** [comment]
Hi @ardeal,

The error you refer to has ERET register set to 0x40039162, but the disassembly doesn't have instructions from this address. Also the code you pasted is not complete - I compiled it with some modification and run on nSIM, and it worked fine, but perhaps modifications that I had to do to make this code compilable also removed the source of error. Maybe it is in i2f function?

What is the hardware platform you are running on? Do you have a TCF file for the core you are using?

Can't answer you last three questions - those are in Claudiu domain :)

**Comment by claziss** [comment]
At this moment, the gcc compiler doesn't support mixing FPX instructions with DSP ones.
