### ISSUE TITLE
Push/Pop instructions are not recognized by the assembler.

### ISSUE THREAD

**Issue by bravindr** [foss-for-synopsys-dwc-arc-processors/gcc#55]
I have been using the following version of the assembler. 
**GNU assembler (ARCompact/ARCv2 ISA elf32 toolchain built on 20160427) 2.23.2**
arc-elf32-as a.s
returns
a.s: Assembler messages:
a.s:101: Error: bad instruction `pop %r11'

where a.s has a  pop instruction. 
Commenting out this instruction prevents this error

**Comment by bravindr** [comment]
The newer version of the assembler seems to have fixed this issue. A working of using ld, instead of pop works fine.

**Comment by bravindr** [comment]
Please read "working" and "workaround" above

**Comment by claziss** [comment]
As it is working in a newer version, I will close this issue.
