### ISSUE TITLE
Processor-Specific Optimizations links to a non-existing page

### ISSUE THREAD

**Issue by jurobystricky** [foss-for-synopsys-dwc-arc-processors/gcc#56]
The page says:
An overview of those options may be found here.

"here" link does not exist. So where can one find the processor specific options?

**Comment by claziss** [comment]
Thank you for feedback. The target specific options description are found in the gcc documentation, which can be found in <your installation folder>/share/doc/gcc (i.e., gcc.pdf), or by invoking gcc with --help=target.  I have updated the wiki page accordingly.
