### ISSUE TITLE
No branch for tag arc-2016.09-release

### ISSUE THREAD

**Issue by jurobystricky** [foss-for-synopsys-dwc-arc-processors/gcc#59]
I noticed the tag arc-2016.09-release (and corresponding commits) is not on any branch. Is this by design?

**Comment by anthony-kolesov** [comment]
Hi,

Yes tag can become detached if original branch was rebased. So one should use "git fetch --tags" to get it, as our scripts do. IIRC Gcc is the only our project to have this specific "feature" for this release, so we'll look into changing that for the next release.

**Comment by anthony-kolesov** [comment]
I have create arc-2016.09 branch which points to arc-2016.09-release.
For the next release I've created arc-2017.03, and changed all release/test processes to use it instead of arc-6.x-dev, so going forward there should be no problems with orphan release tags.
