### ISSUE TITLE
Incorrect documentation for -mea option

### ISSUE THREAD

**Issue by anthony-kolesov** [foss-for-synopsys-dwc-arc-processors/gcc#80]
Doc help specifies for this option:
```
This is always enabled for @option{-mcpu=ARC700}.
```

However https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/blob/arc-2019.09/gcc/config/arc/arc-arches.def#L50 specifies that option is not enabled by default for ARC700, as proved by checking preprocessor defines generated by the compiler.

The documentation in the doc and in the target help also doesn't specify that this option is available only for ARC700.

**Comment by claziss** [comment]
Documents updated here: https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/e735d70a5693c781a1714be79ff0ae9cc2d4b1ba
